name: landcover-mapping
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6  # earthengine doesn't play with python 3.7
  - dataclasses  # only introduced in python 3.7
  - earthengine-api
  - black
  - pytest
  - pytest-flake8
  - pandas
  - xarray
  - netcdf4
  - rasterio
  - matplotlib
  - pip
  - pytorch=1.6.0
  - pyproj
  - tqdm
  - geopandas
  - cartopy
  - scikit-learn
  - pip:
      - pytorch-lightning==0.7.1  # lots of API breaking changes
      - learn2learn==0.1.3
      - dill
