name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
      uses: actions/cache@v1
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: landcover-mapping
        environment-file: environment.yml
        auto-activate-base: false
    - name: Run tests
      run: |
        pytest
        black --check --diff .
